create database autolavado; 
create table VENTA(
id_venta   INT NOT NULL auto_increment,
fecha DATETIME ,
id_cliente INT,
PRIMARY KEY (id_venta)
);
create table CLIENTE(
id_cliente   INT NOT NULL auto_increment,
NOMBRE VARCHAR (30) NOT NULL,
APELLIDO VARCHAR (20) NOT NULL,
TELEFONO   INT,
CORREO_ELECTRONICO VARCHAR (40) NOT NULL,
PRIMARY KEY (id_cliente)
);
create table VEHICULO(
PRIMARY KEY(ID_VEHICULO)
MARCA VARCHAR (30) NOT NULL,
MODELO VARCHAR (30) NOT NULL,
COLOR VARCHAR (30) NOT NULL,
PLACA VARCHAR (30) NOT NULL,
PRIMARY KEY(ID_VEHICULO)
);
create table EMPLEADO(
NO. DE EMPLEADO  (30) INT NOT NULL,
NOMBRE VARCHAR (30) NOT NULL,
TELEFONO VARCHAR (30) INT,
CORREO ELECTRONICO VARCHAR (40) NOT NULL,
PRIMARY KEY(ID_EMPLEADOS)
);
create table SERVICIO(
NOMBRE VARCHAR (30) NOT NULL,
PRECIO DECIMAL (20) INT,
PRIMARY KEY (ID_SERVICIO)
);
create table FACTURA(
ID_FACTURA   INT NOT NULL,
VENTA_ID   INT  NOT NULL,
FECHA DATETIME (10) ,
TOTAL DECIMAL (10) ,
METODO_DE_PAGO VARCHAR (40) NOT NULL,
PRIMARY KEY(FACTURA_ID)
):
PREPARE